# TODO:
# 1. 
# bind C-t new-session -A -s todo "cd ~/projects && nvim TODO.md"
bind C-b last-pane


#set -g @continuum-restore 'on'
# Set bash shell as default
set -g default-shell /usr/bin/bash
set-environment -g PATH "~/bin:$PATH"

# set -g status-right '#{cpu_bg_color} CPU: #{cpu_icon} #{cpu_percentage} | %a %h-%d %H:%M '
set -g status-right '%a %h-%d %H:%M '

# improve colors
set -g default-terminal 'screen-256color'

# Set the status-position option to the top
set-option -g status-position top
# set-option -g status-position bottom

set -g base-index 1


# act like vim
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

bind -T copy-mode-vi "v" send -X begin-selection
bind -T copy-mode-vi "V" send -X rectangle-toggle
bind -T copy-mode-vi "y" send -X copy-selection-and-cancel


# Expand history limit
set -sg escape-time 10
set -g history-limit 65536

#unbind C-b
set -g prefix C-b
bind C-b send-prefix
bind-key C-b send-prefix
bind r source-file ~/.tmux.conf

# use Alt-vim keys to navigate
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# shift 1/2 
bind -n M-1 previous-window 
bind -n M-2 next-window 

# split
bind-key v split-window -h
bind-key g split-window -v

# easy resizing of panes
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

# Set new panes to open in current dir
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# -- Copy Mode ----------------- 
bind -n M-c copy-mode # enter copy mode


# -- Buffers --------------------
# bind b list-buffers     # list paste buffers
bind -n M-v paste-buffer -p  # paste from the top paste buffer
# bind P choose-buffer    # choose which buffer to paste from

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# monitor windows for activity
setw -g monitor-activity on

# clock
setw -g clock-mode-colour colour64 #green

###################################Plugins Downloaded###########################
# if "test ! -d ~/.config/tmux/plugins/tpm" \
#    "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
 
set -g @plugin 'tmux-plugins/tmux-resurrect' # save sesions even after reboot
set -g @plugin 'tmux-plugins/tmux-continuum' # Auto save 

set -g @plugin 'sainnhe/tmux-fzf' # tmux fzf

set -g @plugin 'tmux-plugins/tmux-cpu'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
 
